"use client";

import DashboardWrapper from "../../dashboardWrapper";

interface Task {
  task_id: number;
  title: string;
  description: string;
  status_id: number;
  start_date: string;
  due_date: string;
}

interface Report {
  report_id: number;
  title: string;
  description: string;
  report_type: string;
  generated_by: string;
  generated_at: string;
  report_data: Record<string, any>; // JSONB
  tasks: Task[];
}

const ReportDetailsPage = () => {
  // Dữ liệu tĩnh giống như insert mẫu của bạn
  const report: Report = {
    report_id: 1,
    title: "Task Status Report",
    description: "Báo cáo trạng thái công việc của phòng IT",
    report_type: "TaskStatusByDepartment",
    generated_by: "Admin", // thay bằng tên user nếu muốn
    generated_at: "2025-10-28T10:00:00Z",
    report_data: {
      department: "IT Department",
      total_tasks: 1,
      completed: 0,
      in_progress: 0,
      todo: 1,
    },
    tasks: [
      {
        task_id: 1,
        title: "Setup Database",
        description: "Tạo database và bảng cơ bản",
        status_id: 2, // ví dụ 1=todo, 2=in progress, 3=done
        start_date: "2025-10-20",
        due_date: "2025-10-25",
      },
    ],
  };

  return (
    <DashboardWrapper>
      <div className="w-full">
        <h1 className="text-2xl font-bold mb-2">{report.title}</h1>
        <p className="text-gray-600 dark:text-gray-300 mb-4">
          {report.description}
        </p>
        <p className="mb-2">
          <strong>Type:</strong> {report.report_type}
        </p>
        <p className="mb-4">
          <strong>Generated by:</strong> {report.generated_by} |{" "}
          <strong>Date:</strong>{" "}
          {new Date(report.generated_at).toLocaleString()}
        </p>

        <div className="mb-6">
          <h2 className="text-xl font-semibold mb-2">Summary</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {Object.entries(report.report_data).map(([key, value]) => (
              <div
                key={key}
                className="p-4 bg-gray-100 dark:bg-gray-700 rounded-lg"
              >
                <p className="text-sm text-gray-500">{key}</p>
                <p className="text-lg font-bold">
                  {value !== undefined && value !== null
                    ? typeof value === "object"
                      ? JSON.stringify(value)
                      : String(value)
                    : "-"}
                </p>
              </div>
            ))}
          </div>
        </div>

        <div>
          <h2 className="text-xl font-semibold mb-2">Tasks in this Report</h2>
          <div className="overflow-x-auto">
            <table className="min-w-full bg-white dark:bg-gray-800 rounded-lg">
              <thead>
                <tr className="bg-gray-200 dark:bg-gray-700 text-left">
                  <th className="py-2 px-4">Task ID</th>
                  <th className="py-2 px-4">Title</th>
                  <th className="py-2 px-4">Description</th>
                  <th className="py-2 px-4">Status</th>
                  <th className="py-2 px-4">Start Date</th>
                  <th className="py-2 px-4">Due Date</th>
                </tr>
              </thead>
              <tbody>
                {report.tasks.map((task) => (
                  <tr
                    key={task.task_id}
                    className="border-b border-gray-200 dark:border-gray-600"
                  >
                    <td className="py-2 px-4">{task.task_id}</td>
                    <td className="py-2 px-4">{task.title}</td>
                    <td className="py-2 px-4">{task.description}</td>
                    <td className="py-2 px-4">{task.status_id}</td>
                    <td className="py-2 px-4">{task.start_date}</td>
                    <td className="py-2 px-4">{task.due_date}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </DashboardWrapper>
  );
};

export default ReportDetailsPage;
